sudo: true
language: php
php:
  - 5.6
services:
  - mysql
  - openssl
  - curl
  - session
  - docker
env:
    - CUSTOM_VAR_1=latest CUSTOM_VAR_2=0
addons:
  apt:
    packages:
    - apache2

env:
  global:
    - CORE_BRANCH=master

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  # Disable opcache on PHP 7.0 as it crashes too easily
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ]; then sed -i '/opcache.so/d' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;"
  - php --modules

  # Setup Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  #- wget https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.0.jar
  #- java -jar selenium-server-standalone-2.47.0.jar -port 4444 >/dev/null 2>&1 & # WARNING - Takes a long time to start up. Keep here
  #- java -jar selenium-server-standalone-2.47.0.jar -port 4444
  #- sleep 5

  - php -S 0.0.0.0:8000 &
  # in new terminal window
  - docker run -i -t -p 4444:4444 -e APP_PORT=8000 davert/selenium-env >/dev/null 2>&1 &

before_script:  
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-fastcgi php5-curl php5-mysql php5-intl php5-gd > /dev/null
  - sudo mkdir $(pwd)/.run
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo sed -e "s,listen = 127.0.0.1:9000,listen = /tmp/php5-fpm.sock,g" --in-place ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo sed -e "s,;listen.owner = nobody,listen.owner = $USER,g" --in-place ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo sed -e "s,;listen.group = nobody,listen.group = $USER,g" --in-place ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo sed -e "s,;listen.mode = 0660,listen.mode = 0666,g" --in-place ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo sed -e "s,user = nobody,;user = $USER,g" --in-place ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo sed -e "s,group = nobody,;group = $USER,g" --in-place ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f tests/travis-ci-apache.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - git submodule update --init --recursive
  - sudo service apache2 restart

  # Fluxbox
  - sudo apt-get install fluxbox -y --force-yes
  - fluxbox &
  - sleep 3 # give fluxbox some time to start

  # Make sure Webdriver is running
  - curl http://localhost:4444/wd/hub/status
  - curl http://127.0.0.1:4444/wd/hub/static/resource/hub.html

  # Disable xdebug when we don't need coverage to speed up testing
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' ]; then phpenv config-rm xdebug.ini; fi;"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' != 'mysql' ]; then phpenv config-rm xdebug.ini; fi;"
  # Composer
  - composer self-update
  - composer update
  #- composer install -o --prefer-dist --no-interaction
  #- composer show -i

script:

  # Acceptance tests, using Firefox, without code coverage
  - php vendor/bin/codecept bootstrap
  - php vendor/bin/codecept build
  #- php ~/build/fulldecent/pmtsystem/codeception/vendor/codeception/codeception/codecept run acceptance --steps --html
  - mv -f tests/acceptance.suite.sample.yml tests/acceptance.suite.yml
  - cat tests/acceptance.suite.yml
  - php vendor/bin/codecept run acceptance
  # Unit, integration and api tests, without code coverage
  #- sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' ]; then php vendor/bin/codecept run api,integration,unit; fi;"
  #- sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' != 'mysql' ]; then php vendor/bin/codecept run api,integration,unit; fi;"

  # PHP 5.6 ONLY: Unit, integration and api tests with code coverage
  #- sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' = 'mysql' ]; then php vendor/bin/codecept run api,integration,unit --coverage --coverage-xml --coverage-html; fi;"
  # We can't use phpdbg only as it doesn't work with the webdriver and we can't use it for some tests only as we can't merge html reports
  # - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' = 'mysql' ]; then phpenv config-rm xdebug.ini; phpdbg -qrr vendor/bin/codecept run api,integration,unit --coverage --coverage-xml --coverage-html; fi;"

after_failure:
  - curl http://127.0.0.1:4444/wd/hub/static/resource/hub.html
  # '/home/travis/build/kuflievskiy/test-codeception-on-travis/tests/_output
  - curl http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer
notifications:
  email:
    kuflievskiy@gmail.com
