sudo: false

language: php
php:
  - 5.6
services:
  - mysql
  - openssl
  - curl
  - session
env:
    - CUSTOM_VAR_1=latest CUSTOM_VAR_2=0
addons:
  apt:
    packages:
    - apache2

env:
  global:
    - CORE_BRANCH=master

branches:
  only:
    - master
    - development	
    - /^stable\d+(\.\d+)?$/

before_install:
  # Disable opcache on PHP 7.0 as it crashes too easily
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ]; then sed -i '/opcache.so/d' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;"
  - php --modules
  - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar

before_script:

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - java -jar selenium-server-standalone-2.48.2.jar -port 4444 >/dev/null 2>&1 &
  - sleep 5

  - mysql -e 'CREATE DATABASE testdb CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;'
  - php -S 0.0.0.0:8000 &
  - stty cols 160

  # Disable xdebug when we don't need coverage to speed up testing
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' ]; then phpenv config-rm xdebug.ini; fi;"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' != 'mysql' ]; then phpenv config-rm xdebug.ini; fi;"
  # Composer
  - composer self-update
  - composer update

script:

  # Run Codeception Acceptance tests
  - php vendor/bin/codecept bootstrap
  - php vendor/bin/codecept build
  - mv -f tests/acceptance.suite.sample.yml tests/acceptance.suite.yml
  - cat codeception.yml
  - mv -f codeception.sample.yml codeception.yml
  - cat tests/acceptance.suite.yml
  - php vendor/bin/codecept run acceptance --steps --html

notifications:
  email:
    kuflievskiy@gmail.com
