sudo: false

language: php
php:
  - 5.6
  - 7  
services:
  - mysql
  - openssl
  - curl
  - session
  - docker
env:
    - CUSTOM_VAR_1=latest CUSTOM_VAR_2=0
addons:
  apt:
    packages:
    - apache2

env:
  global:
    - CORE_BRANCH=master

branches:
  only:
    - master
    - development	
    - /^stable\d+(\.\d+)?$/

before_install:
  # Disable opcache on PHP 7.0 as it crashes too easily
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ]; then sed -i '/opcache.so/d' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;"
  - php --modules
before_script:
  - mysql -e 'CREATE DATABASE testdb CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;'
  - php -S 0.0.0.0:8000 &
  - docker run -i -t -p 4444:4444 -e APP_PORT=8000 davert/selenium-env
  # Disable xdebug when we don't need coverage to speed up testing
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' ]; then phpenv config-rm xdebug.ini; fi;"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' != 'mysql' ]; then phpenv config-rm xdebug.ini; fi;"
  # Composer
  - composer self-update
  - composer update

script:

  # Run Codeception Acceptance tests
  - php vendor/bin/codecept bootstrap
  - php vendor/bin/codecept build
  - mv -f tests/acceptance.suite.sample.yml tests/acceptance.suite.yml
  - cat codeception.yml
  - mv -f codeception.sample.yml codeception.yml
  - cat tests/acceptance.suite.yml
  - php vendor/bin/codecept run acceptance --steps --html

notifications:
  email:
    kuflievskiy@gmail.com
